### ISSUE TITLE
Typhoon Ruby initial request - eastern shore areas from adjusted track

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#1]
Pulling the adjusted track priority areas from the HOT imagery list into a ticket. From the priority requests [24](http://hirc.dev.hotosm.org/requests/24/), [25](http://hirc.dev.hotosm.org/requests/25/), and [26](http://hirc.dev.hotosm.org/requests/26/), below is a quick grab some of the best recent imagery. Some of these images have significant clouds inland, but have clear sections over cities and coastline. 

| Catalog ID | Sensor | Acquisition Date |
| --- | --- | --- |
| [10400100044BAB00](https://browse.digitalglobe.com/imagefinder/showBrowseMetadata?catalogId=10400100044BAB00) | WV3 | 11-07-2014 |
| [1040010004CC9300](https://browse.digitalglobe.com/imagefinder/showBrowseMetadata?catalogId=1040010004CC9300) | WV3 | 11-07-2014 |
| [104001000410BD00](https://browse.digitalglobe.com/imagefinder/showBrowseMetadata?catalogId=104001000410BD00) | WV3 | 11-07-2014 |
| [104001000271F300](https://browse.digitalglobe.com/imagefinder/showBrowseMetadata?catalogId=104001000271F300) | WV3 | 10-07-2014 |
| [10400100024B8A00](https://browse.digitalglobe.com/imagefinder/showBrowseMetadata?catalogId=10400100024B8A00) | WV3 | 10-07-2014 |
| [1020010033480C00](https://browse.digitalglobe.com/imagefinder/showBrowseMetadata?catalogId=1020010033480C00) | WV1 | 07-12-2014 |
| [1020010032441400](https://browse.digitalglobe.com/imagefinder/showBrowseMetadata?catalogId=1020010032441400) | WV1 | 07-12-2014 |
| [103001002E290A00](https://browse.digitalglobe.com/imagefinder/showBrowseMetadata?catalogId=103001002E290A00) | WV2 | 04-04-2014 |

@MarkCupitt - the first three are focus on request 25 and seem to be fairly clear. Give a quick preview to check if these cover the AOI well based on your request and if these will work well for initial images.

**Comment by MarkCupitt** [comment]
_@smit1678_ These all  look Great for initial images. We are preparing Tasks now, let me know when/how Imagery will be available, license made available under and required attributions.
Thanks

**Comment by smit1678** [comment]
@MarkCupitt Based on your note to the list, here are some new scenes that could be used: 

| Catalog ID | Sensor | Acquisition Date |
| --- | --- | --- |
| [1020010033480C00](https://browse.digitalglobe.com/imagefinder/showBrowseMetadata?catalogId=1020010033480C00) | WV1 | 07-12-2014 |
| [1020010032441400](https://browse.digitalglobe.com/imagefinder/showBrowseMetadata?catalogId=1020010032441400) | WV1 | 07-12-2014 |

**Comment by MarkCupitt** [comment]
Hi Nate, here is our Wishlist Poly for now. We are still waiting on the track confirmation, but this area is high probability of being part of the track in some way. Priority would be to the North, especially the islands.

Cannot Upload GeoJson, but here is a link to my Gist

https://gist.github.com/MarkCupitt/9c58b429b279b59040b5

**Comment by MarkCupitt** [comment]
Hi Nate

Here is a secondary Wish list in case the track heads up towards Manila

https://gist.github.com/MarkCupitt/31f57cb5140d6ce23744

**Comment by smit1678** [comment]
Closing this out. This is old now.
