### ISSUE TITLE
Portiion of HOT Project #2501 not covered by hires imagery

### ISSUE THREAD

**Issue by bgirardot-np** [hotosm/imagery-requests#103]
* **Description:**
This imagery is needed to complete http://tasks.hotosm.org/project/2501 Tanzania Development Trust mapping to combat female genital mutilation. Approximately 25% of the project area has no hires imagery available. This is a very large project area and their target completion date is fall of 2017 (they missed fall of 2016 original goal). The project is map roads, buildings, residential areas.

Both Bing and Mapbox only have low resolution imagery. DigitalGlobe +Vivid does have good imagery for the area.  Well intentioned folks made use of DG +Vivid from a different HOT project. We have put a stop to that but are hoping we might receive permission to use it to complete the project.

* **Wiki link:** This is an ongoing project not part of an activation, see the project description http://tasks.hotosm.org/project/2501 for links to project information.

* **Request extent**: https://gist.github.com/bgirardot-np/38eab7d5ed90fae560056be70ade470a

![2017-03-23_03h04_40](https://cloud.githubusercontent.com/assets/12796805/24228588/84f2de78-0f75-11e7-9bbc-b1c7aa3492a1.png)

* **Issue with current imagery quality:**
	- [ ] Clouds
	- [ ] Blank tiles (no imagery)
	- [ ] Black and white imagery
	- [ ] Outdated imagery
	- [x] Other:   Low res imagery only.

* **Level of urgency:**
	- [ ] Low
	- [x] Medium
	- [ ] High

* **Requirement of Post imagery:**
 - [ ] Yes
 - [x] No

**Comment by bgirardot** [comment]
The new DG Standard Layer made available to OSM covers this request. I notified those involved and am closing this. Thank you @DigitalGlobe
