### ISSUE TITLE
Search functionality to map views

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#110]
Feedback from user testing: add search bar functionality to map views. Difficult to find very small places or islands when all you have it zooming and panning on the map. This is helpful for the Imagery Search view as well as when defining the AOI for the task.

**Comment by brendangatens** [comment]
Yup, let’s try and add the same search bar that we plan on using ([this one](https://marvelapp.com/350efei/screen/31936237)) on map.openaerialmap.org across all maps. In the case that we have a search that will affect multiple maps, that search bar will need to be brought out of the map boundaries ([like so](https://marvelapp.com/23ef2ie/screen/32131157)).
