### ISSUE TITLE
Improve visibility of descriptive help text

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#115]
Feedback from user test: help notes on the Request Form are slightly hidden. Notes were not immediately read when they are below the input box. Could be helpful to have them higher up or exposed differently to ensure readability. 

![hotosm imagerycoord 2017-06-12 11-43-14](https://user-images.githubusercontent.com/796838/27030502-6e3c3af6-4f64-11e7-8369-2f869fc03e66.png)

**Comment by brendangatens** [comment]
I’d like to see the help text moved above the form field (but below the label). If we think that this creates a disconnect between the label and its associated field, I would increase the spacing between each form group.
