### ISSUE TITLE
Improve how to draw or add a task AOI

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#116]
Feedback from user test: slight confusion on how to draw or add a task AOI. Drawing buttons were slightly hidden on the right side and there was no descriptive help text. 

![hotosm imagerycoord 2017-06-12 11-46-38](https://user-images.githubusercontent.com/796838/27030643-f2f6185c-4f64-11e7-8570-9af12ac8e0f4.png)

**Comment by sharkinsspatial** [comment]
Could things be clarified by moving the drawing control buttons out of the map into the create task section?  All of the AOI operations (choose file or draw) would then be logically contained.

**Comment by smit1678** [comment]
From #141, the new edit AOI operations are in place. First take on the UI is as follows: 

![img-coord-edit-test](https://user-images.githubusercontent.com/796838/29037875-61b3cae6-7b9d-11e7-8808-053bce12657f.gif)

@sharkinsspatial I like the help text changing and providing guidance to the user. One point of feedback when I first edited: I only had a mouse change to know that I could edit. Help text is nice, but was confused for just one second when I didn't see an edit polygon button (but that's coming from a user who expected that). 

Do we want to think about having both help text plus buttons like this example? https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/

@brendangatens Do you have some suggestions for small improvements?

**Comment by sharkinsspatial** [comment]
@smit1678 @brendangatens.  I'm up for whatever you guys feel is the most intuitive for the user here.  We can definitely  have a button users need to click in order to enable drawing.  I omitted it in this initial cut as it seemed like extra step rather than dropping the user directly into draw mode, but both either approach is relatively easy to set up.
