### ISSUE TITLE
Limit task size

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#121]
Feedback from user test: limit task AOI size when creating a new task. It may be helpful when creating tasks for UAVs to limit the size you can create. 

This will be difficult to set to one size because of varying capabilities of UAV models, but marking here to discuss and evaluate what makes the most sense.

**Comment by smit1678** [comment]
To do: determine reasonable limit for UAVs and satellite imagery

**Comment by smit1678** [comment]
@cgiovando what kind of area would you suggest for UAVs versus satellite imagery? 

Upon thinking about this more, I think I would suggest that we only display warnings based on if UAV or satellite imagery are the type of collection platform. Hard limitations may make edge cases difficult from a user experience perspective.

**Comment by sharkinsspatial** [comment]
Displaying different size warning based on product types will require a small change to the [API](https://github.com/hotosm/imagery-coordination-api/blob/b24b7c092d451654940bdf6bb9e263be0ed06a0b/app/utils/utils.js ) to include the product information from the parent request in the returned task. 
 Not sure how you want to coordinate pull requests across repositories?

**Comment by smit1678** [comment]
👍  ok that makes sense; I can help coordinate with you. The staging front-end is a connected to a staging API that is running the `develop` branch. So we can test deploy there. I can help test anything locally first as well.

**Comment by sharkinsspatial** [comment]
@smit1678 @cgiovando Do we have a limit in square meters I can use for this?  There should be one for UAV and then one for everything else.

**Comment by cgiovando** [comment]
Hey @smit1678 @sharkinsspatial - I think warning may be OK, but I would not set any arbitrary limit. There are different factors that will impact the capacity of providers to cover AOIs with specific platforms and sensor combinations. Listing some here, then we should look at potentially integrating with flight planning software models for UAVs.

- GSD: a higher target resolution would require either bigger sensors or flying lower, increasing flight time per sqm;
- Regulations: flying beyond line of sight and above standard ceiling allows to cover much larger areas with capable UAVs. Rules change country by country (and sometime locally), but would be important to factor when warning about AOI size;
- Accessibility: related to the above, for sites with limited access (dense forest, river crossing, private property, etc), it would impact the AOIs size.
- Platform: fixed wing vs rotary UAV is obviously one factor, but even with fixed wing aircraft, there are different sizes, payload capacity and propulsion that will affect the range.

There can be more to add to this list, but I would say for small "individual" daily surveys with standard sensors and ceiling, 1 sqkm AOIs are generally considered large.

**Comment by smit1678** [comment]
@cgiovando Yes, exactly why a warning is better than a strict limit. So here's what I propose to start with: 

UAV: warning at 1sqkm
Satellite imagery: 1000sqkm
