### ISSUE TITLE
Chin State - Multi hazards Risk Assessment, ADPC

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#127]
* **Description:**
	_Current available satellite imagery layers are old or low-resolution - Mapbox age seems to be 2009 DG WV1 imagery. Task #3257 is in need of updated, high resolution imagery in order to digitize buildings into OpenStreetMap. The project is focused on generating buildings for a multi-hazard risk assessment being conducted by the Asian Disaster Preparedness Center._

* **Wiki link:** _not an activation_

* **Request extent**: https://coordination.openaerialmap.org/#/requests/596c7cc8eb38a400111f12b2

* **Issue with current imagery quality:**
	- [ ] Clouds
	- [ ] Blank tiles (no imagery)
	- [x] Black and white imagery
	- [x] Outdated imagery
	- [x] Other: low resolution in some areas. Link to imagery comparison here: https://coordination.openaerialmap.org/#/imagery-search/93.63241121808045,22.639824200949406,12

* **Level of urgency:**
	- [ ] Low
	- [x] Medium
	- [ ] High

* **Requirement of Post imagery:**
 - [ ] Yes
 - [x] No

**Comment by smit1678** [comment]
These DG CatIDs would probably be ideal for recency, low clouds, and covers the AOI: 

1030010066C7CF00
103001006654F300
1030010065AAF200
1030010065B25600

WV02 imagery dated Mar 3, 2017

**Comment by d3netxer** [comment]
We finished processing the imagery and sent out the imagery service

**Comment by smit1678** [comment]
I updated and closed out the request on Coordination: https://coordination.openaerialmap.org/#/requests/596c7cc8eb38a400111f12b2
