### ISSUE TITLE
Investigate sprite issue with Mapbox Light style.

### ISSUE THREAD

**Issue by sharkinsspatial** [hotosm/imagery-requests#139]
Currently the application is requesting raster tiles for the Mapbox Light style rather than leveraging the vector tiles directly.  After some investigating switching I noticed that there are issues with the current style returning 401 errors for sprites at some zoom levels (probably related to using an outdated Mapbox base style).  Someone with access to the Mapbox Studio account will need to investigate further.

**Comment by smit1678** [comment]
@sharkinsspatial I wasn't sure on where the issue was coming from (couldn't replicate) so I just republished the existing basemap we were using to see if that helps. But also created a brand new style to test to see if this fixed it because of an outdated style: 

```
https://api.mapbox.com/styles/v1/hot/cj5s2w83i3clm2spki06znox2.html?title=true&access_token=pk.eyJ1IjoiaG90IiwiYSI6ImNpeXEwbHF2aTAwMDcycW10dGs4Z28wdGYifQ.p9gO4DrmIw1zBIKhvtIivw#2.3/10.389575/12.686800/0
```

**Comment by sharkinsspatial** [comment]
Hi Nate:
I tracked down the issue to a Mapbox token in the config files which was no longer valid.  Thanks.
