### ISSUE TITLE
Post-EQ DG imagery available for Ecuador

### ISSUE THREAD

**Issue by maning** [hotosm/imagery-requests#21]
Stub ticket to coordinate preparation of TMS for post-EQ imagery.
Download resources: http://www.digitalglobeblog.com/2016/04/19/open-imagery-and-data-to-support-ecuador-earthquake-response/

**Comment by smit1678** [comment]
Thanks @maning. 

To capture what's been on the list and summarize a few things to update: 
- Umap with pre-disaster imagery footprints + HOT tasks is here: http://umap.openstreetmap.fr/en/map/2016-ecuador-earthquake_81488
- I've posted footprints of available post-disaster imagery from DG in the umap
- I'm looking into making the imagery available in OAM (imagery is not-pansharpened at the moment) 

Next up: 
- [ ] render TMS. @lossyrob is looking into rendering a TMS through OAM 

Anything else to update?

**Comment by hyances** [comment]
OK.  Please send me TMS URL when is ready.  I've not seen coberture polygons in Umap, do you have a link with geojson?

**Comment by pratikyadav** [comment]
https://gist.github.com/pratikyadav/5aa734027fc48539850ec8e9ec26bdcb
Some observation based on 👀  the DG imagery. 

cc @smit1678

**Comment by smit1678** [comment]
@pratikyadav 👍 this is a great recap. 

To update on where we're at (chat here https://gitter.im/hotosm/OpenAerialMap): 
- @nbumbarger has been doing some pansharpening of the priority area 1
- @lossyrob has been working on a TMS 

Should have a progress update on next steps here shortly.

**Comment by lossyrob** [comment]
Currently working through some rendering issues, should have a TMS of the following images pretty soon (without pan sharpening). The biggest issue I'm having is getting decent coloring out of the images, so if someone has a good way of color correcting these UInt16 images let me know!

```
      "s3://ecuador-earthquake/post-event/055228871010_01/055228871010_01_P001_MUL/16APR19153535-M1BS-055228871010_01_P001.TIF",
      "s3://ecuador-earthquake/post-event/055228871010_01/055228871010_01_P002_MUL/16APR19153537-M1BS-055228871010_01_P002.TIF",
      "s3://ecuador-earthquake/post-event/055228868010_01/055228868010_01_P001_MUL/16APR19161450-M1BS-055228868010_01_P001.TIF",
      "s3://ecuador-earthquake/post-event/055228868010_01/055228868010_01_P002_MUL/16APR19161452-M1BS-055228868010_01_P002.TIF",
      "s3://ecuador-earthquake/post-event/055228868010_01/055228868010_01_P003_MUL/16APR19161454-M1BS-055228868010_01_P003.TIF",
      "s3://ecuador-earthquake/post-event/055228868010_01/055228868010_01_P004_MUL/16APR19161456-M1BS-055228868010_01_P004.TIF",
      "s3://ecuador-earthquake/post-event/055228868010_01/055228868010_01_P005_MUL/16APR19161457-M1BS-055228868010_01_P005.TIF",
      "s3://ecuador-earthquake/post-event/055228868010_01/055228868010_01_P006_MUL/16APR19161459-M1BS-055228868010_01_P006.TIF",
      "s3://ecuador-earthquake/post-event/055228868010_01/055228868010_01_P007_MUL/16APR19161501-M1BS-055228868010_01_P007.TIF",
      "s3://ecuador-earthquake/post-event/055228868010_01/055228868010_01_P008_MUL/16APR19161503-M1BS-055228868010_01_P008.TIF",
      "s3://ecuador-earthquake/post-event/055228868010_01/055228868010_01_P009_MUL/16APR19161504-M1BS-055228868010_01_P009.TIF",
      "s3://ecuador-earthquake/post-event/055228869010_01/055228869010_01_P001_MUL/16APR19161431-M1BS-055228869010_01_P001.TIF",
      "s3://ecuador-earthquake/post-event/055228869010_01/055228869010_01_P002_MUL/16APR19161433-M1BS-055228869010_01_P002.TIF",
      "s3://ecuador-earthquake/post-event/055228869010_01/055228869010_01_P003_MUL/16APR19161434-M1BS-055228869010_01_P003.TIF",
      "s3://ecuador-earthquake/post-event/055228869010_01/055228869010_01_P004_MUL/16APR19161436-M1BS-055228869010_01_P004.TIF",
      "s3://ecuador-earthquake/post-event/055228869010_01/055228869010_01_P005_MUL/16APR19161438-M1BS-055228869010_01_P005.TIF",
      "s3://ecuador-earthquake/post-event/055228869010_01/055228869010_01_P006_MUL/16APR19161439-M1BS-055228869010_01_P006.TIF",
      "s3://ecuador-earthquake/post-event/055228869010_01/055228869010_01_P007_MUL/16APR19161441-M1BS-055228869010_01_P007.TIF",
      "s3://ecuador-earthquake/post-event/055228869010_01/055228869010_01_P008_MUL/16APR19161443-M1BS-055228869010_01_P008.TIF",
      "s3://ecuador-earthquake/post-event/055228869010_01/055228869010_01_P009_MUL/16APR19161443-M1BS-055228869010_01_P009.TIF",
      "s3://ecuador-earthquake/post-event/055228082010_01/055228082010_01_P001_MUL/16APR17160246-M1BS-055228082010_01_P001.TIF",
      "s3://ecuador-earthquake/post-event/055228082010_01/055228082010_01_P002_MUL/16APR17160248-M1BS-055228082010_01_P002.TIF",
      "s3://ecuador-earthquake/post-event/055228082010_01/055228082010_01_P003_MUL/16APR17160250-M1BS-055228082010_01_P003.TIF"
```

**Comment by lossyrob** [comment]
This is what I've gotten so far: 

http://oam-tiles.s3.amazonaws.com/ecuador-earthquake-nopan-2/{z}/{x}/{y}.png

Static PNG tiles from zoom 17 up.

You can see what I mean about the coloring issue. I'm simply rescaling the UInt16 images to Bytes, and clearly that's not a proper color correction. Also there's some resampling artifacts that I can get rid of. I'm going to continue to work on improving the map.

/cc @hyances

**Comment by hyances** [comment]
OK, here **priority** for post-event mapping projects:
- highways between populated places (only)
- identify broken roads and bridges.

So I think we can open TM project with a wide area, because instructions are very simple and fast to map.  We can focus on priority area #1.  Any volunteer to create first project (in draft) with this?

Please, let me check before launching,

Thanks,

Humberto

**Comment by hyances** [comment]
OK, seems main imagery is not load yet ![](https://dl.dropboxusercontent.com/u/1720266/indice.jpeg)

**Comment by smit1678** [comment]
@hyances Yeah, I wouldn't use this imagery yet. Still need to get the colors and artifacts fixed before putting this out to be used.

**Comment by lossyrob** [comment]
This is the Priority 1 imagery, pan sharpened and color corrected by others, tiled through the OAM tiler.

http://oam-tiles.s3.amazonaws.com/ecuador-earthquake-priority-1/{z}/{x}/{y}.png

The remaining issues are:
- There is some strange coloring in various places, seems to happen around clouds. I can't find where this would be caused by the tiler; potentially this is the color correction, but of course I could be missing something in the code.
- There is no alpha band in the corrected imagery, so in order for the area surrounding the imagery to be transparent, the places where pixels drop to RGB (0, 0, 0) are also transparent.

Let me know when other imagery is available and I can run this process over them.

**Comment by lossyrob** [comment]
The two Priority 1 area images

http://beta.openaerialmap.org/#/-80.52978515625,-1.0762535361398837,11/2100011032111/571975932b67227a79b4faf4
http://beta.openaerialmap.org/#/-80.61767578124999,-0.9444381245910761,11/2100011030303/571975932b67227a79b4faf5

both shown in the TMS endpoint

http://oam-tiles.s3.amazonaws.com/ecuador-earthquake-priority-1.2/{z}/{x}/{y}.png

are available in OAM.
