### ISSUE TITLE
DRC Imagery Request: Updated imagery for refugee camps for UNHCR

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#24]
Request via imagery-coord mailing list from Claire Halleux. 
- **Description:**

> UNHCR has requested the mapping of several camp areas.
> Therefore we are looking for updated imagery over these areas.
> 
> The earlier the better, as it will help the operations on the ground.
> 
> Any time within 2016 should suffice to start the mapping. However, as this camp is still continuously evolving, the most recent date available would be best.
- **Wiki link:** na
- **Request extent**: Three AOIs (Boyabo, Bili, Lusenda): https://gist.github.com/smit1678/1771a4ce7c7948d8eddaf16ec74d8dc4
  - ![fireshot capture 024 - drc imagery request - july 2016_ - https___gist github com_smit1678_1](https://cloud.githubusercontent.com/assets/796838/16804322/18768bfc-4903-11e6-8a4e-874a4bf90582.png)
- **Issue with current imagery quality:**
  - [ ] Clouds
  - [ ] Blank tiles (no imagery)
  - [ ] Black and white imagery
  - [x] Outdated imagery
  - [ ] Other:   _please fill in description here_
- **Level of urgency:**
  - [ ] Low
  - [x] Medium
  - [ ] High
- **Requirement of Post imagery:**
  - [ ] Yes
  - [x] No

**Comment by bensonwilder** [comment]
State Department MapGive is conferring with Population, Refugees, and Migration Bureau and plans to support.

**Comment by d3netxer** [comment]
scoped out:
- Billi : 20160126_billi_WV3 1040010017431F00
- boyabo: boyabo_21feb16_WV3   1040010017A77B00
- lusenda_26jun16_WV2   1030010056C5CB00

loading to library...

**Comment by d3netxer** [comment]
IttC service completed. Will e-mail out TMS links
