### ISSUE TITLE
Develop sitemap

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#29]
via @ascalamogna to begin functionalities, pages, and app flow -- First version of the imagery request app sitemap. 

![oam-coordination-app-sitemap](https://cloud.githubusercontent.com/assets/796838/19804669/b077be64-9d07-11e6-9a37-30854ba91f06.jpg)

Next actions, need to answer: 
- Does this meet the goals of the app?
- Is any content or functionality missing?

Also need to answer: 
- Who are the main users coming to the public homepage?
- How much can be public on the homepage?
- How many tasks might a surveyor be assigned at a time?
- What is the typical time frame for completing a task?
- How many different statuses will there be?
- What metadata will be added for each task?
- What makes sense to filter tasks by?
- Should we considering add commenting functionality to the tasks?

cc @hotosm/imagery-request-app

**Comment by smit1678** [comment]
@ascalamogna I started a shared google doc with the questions to start to fill in: https://docs.google.com/document/d/1DxFwmsjCtXttYebtc4uVdZb28m7DMvX7YbkdV7R18hI/edit?usp=sharing. 

cc @cgiovando

**Comment by ascalamogna** [comment]
@smit1678 @cgiovando 

Here's an updated sitemap based on the discussion we had this week. Let me know if you have any questions.

![coordination-app-sitemap_v2](https://cloud.githubusercontent.com/assets/6752098/20014557/65b7597c-a2af-11e6-8d31-2cdb0595302d.png)

cc @olafveerman @danielfdsilva
