### ISSUE TITLE
Metadata requirements for each request

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#30]
First take at metadata for each request. This would include both information needed up front for a request as well as the status updates. @cgiovando @danielfdsilva Suggestions for other items to be included here? 

element | type | description
--- | --- | ---
uuid | string | Unique identifier generated by application
project | string | Event name or Tasking Manager project ID
time_period_requested | string | Date range requested
time_period_provided | string | Date range (or specific date) that was captured
purpose | string | Description of the purpose of the request
intended_use | string | Description of the outputs to be generated from the imagery
delivery_time | string | Time frame for delivery
aoi_requested | string | Extent of area needed, WKT or BBOX?
aoi_collected | string | Extent of area collected, WKT or BBOX?
status | object | Status of the request

**Comment by cgiovando** [comment]
I would add:
- requesting organization
- desired / required GSD
- compression (if any)
- product type (RGB, NIR, etc)
- min acceptable accuracy
- required license
- max cloud cover
- preferred provider
- preferred platform/sensor
- linked tasks
- notes

Some of these could be made optional avoid overcomplicating the request
process.

**Comment by smit1678** [comment]
@cgiovando Thanks, good catch on these. Thinking perhaps we start minimal so we'd prioritize for task generation and management these three: 
- requesting organization
- desired / required GSD
- product type (RGB, NIR, etc)

The others could be optional and then considered in the future for feature additions for any UI elements: 
- compression (if any)
- min acceptable accuracy
- required license
- max cloud cover
- preferred provider
- preferred platform/sensor
- linked tasks
- notes

**Comment by smit1678** [comment]
Splitting this into request and task metadata (I think this should capture both how we're structuring request as well as keeping the metadata simple): 

## Request

| element | type | description |
| --- | --- | --- |
| uuid | string | Unique identifier generated by application |
| project | string | Event name or Tasking Manager project ID |
| time_period_requested | string | Date range requested |
| purpose | string | Description of the purpose of the request |
| intended_use | string | Description of the outputs to be generated from the imagery |
| aoi_requested | string | Extent of area needed, WKT or BBOX? |
| status | string | Status of the request (open, closed, canceled) |
| progress | number | Percentage complete |
| requesting organization | string | Organization requesting imagery |
| desired / required GSD | number | Desired resolution |
| product type (RGB, NIR, etc) | string | Desired type of imagery |
| other_properties | object | other requested information |
| tasks | object | Tasks within the request |
| created_by | string | User that created the request |

## Tasks

| element | type | description |
| --- | --- | --- |
| task_uuid | string | Unique identifier generated by application |
| time_period_provided | string | Date range (or specific date) that was captured |
| delivery_time | string | Time frame for delivery |
| task_aoi_requested | string | Extent of area collected, WKT or BBOX? |
| task_aoi_collected | string | Extent of area collected, WKT or BBOX? |
| status | object | Status of the request |
| assigned_to | string | User assigned |

**Comment by danielfdsilva** [comment]
Closing in favor of #33
