### ISSUE TITLE
Tech stack

### ISSUE THREAD

**Issue by danielfdsilva** [hotosm/imagery-requests#32]
This is the tech stack we propose to use for the imagery request App:

**Backend** (node js)
- [Hapi](http://hapijs.com/) routing and api core
- [Auth0](https://auth0.com/) third party service to manage authentication and users
- PostgresSQL database

**Frontend**
- [React](https://facebook.github.io/react/) + [Redux](http://redux.js.org/) as fronted framework.
- [Mapbox gl](https://www.mapbox.com/mapbox-gl-js/api/) as mapping library

**Comment by smit1678** [comment]
> Auth0 third party service to manage authentication and users

Is it possible to leverage their [custom OAuth integrations](https://auth0.com/docs/connections/social/oauth2) so we can add [OSM OAuth](https://wiki.openstreetmap.org/wiki/OAuth) as a method?

**Comment by kamicut** [comment]
@smit1678 It's possible, I've seen it [here](http://stevecoast.com/2016/05/12/connecting-wordpress-to-openstreetmap-with-auth0/)

**Comment by sethfitz** [comment]
> Mapbox gl as mapping library

How well does this work with raster layers, e.g. to display existing imagery from a tiled endpoint?

> PostgresSQL database

Other components already use MongoDB (right?). Why something new / different?

Do you envision using RDS, Heroku Postgres, or running a database server on the same instance as the app? Can the app be deployed in a shared environment (or using Lambda, per https://aws.amazon.com/blogs/aws/running-express-applications-on-aws-lambda-and-amazon-api-gateway/) as to not need its own instance?

**Comment by danielfdsilva** [comment]
@mojodna Mapbox gl handles raster tiles pretty well. ([example](https://www.mapbox.com/mapbox-gl-js/example/map-tiles/)).
You're right regarding the DB, and I'd say we can continue with MongoDB.

We haven't discussed deployment yet, but it could be deployed in a shared environment as long as it runs node and the db is present.
