### ISSUE TITLE
Nepal earthquake - identify priority locations

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#6]
Starting a thread to gather priority locations for imagery requests. 

uMap for tracking areas started here: http://umap.openstreetmap.fr/en/map/2015-nepal-earthquake_37675#9/27.6531/85.9982

To do: 
- [x] identify areas
- [x] draw areas on [uMap](http://umap.openstreetmap.fr/en/map/2015-nepal-earthquake_37675#9/27.6531/85.9982)
- [x] ticket out individual requests in separate threads here

**Comment by mikelmaron** [comment]
@smit1678 I updated the uMap link, just created one at http://umap.openstreetmap.fr/en/map/2015-nepal-earthquake_37675#9/27.6531/85.9982

Can you ping imagery-coord? We need to identify areas where Bing/MapBox are lacking. Some reports already http://tasks.hotosm.org/project/994#task/6

**Comment by mikelmaron** [comment]
Bing analyser says significant gaps in coverage in region http://ant.dev.openstreetmap.org/bingimageanalyzer/?lat=27.82328839626378&lon=85.70709228515625&zoom=9&l=osm

**Comment by smit1678** [comment]
@mikelmaron excellent, thanks. imagery-coord pinged.

**Comment by smit1678** [comment]
Added a layer showing Bing low-res areas: http://umap.openstreetmap.fr/en/map/2015-nepal-earthquake_37675#9/27.8706/85.4187

**Comment by mikelmaron** [comment]
We need to evaluate the exact gap in coverage in Bing and MapBox, and submit a request. Processing can start asap

**Comment by d3netxer** [comment]
I drew a purple polygon, what do you think of trying to get imagery over here first? 
http://umap.openstreetmap.fr/en/map/2015-nepal-earthquake-contributions-via-the-task-m_37675#9/28.2681/84.6112

Also, it would be good to cover the imagery gap where There is No Bing or Mapbox Hi-res imagery, that red polygon, I'll have to double check to see if any good imagery can be gotten here.

**Comment by smit1678** [comment]
@d3netxer Cool, I just dropped in a potential image for the red section. 

Going to break these priority areas out into separate tickets to track any processing.

**Comment by AndrewBuck** [comment]
I updated the missing imagery polygons on the umap.  It looks like they were drawn from the bing analyzer, which gets out of date as new bing imagery comes on line.  So some were covered with Bing already, and some actually have medium resolution imagery from mapbox (in black and white).  I made the ones where mapbox is available in teal, and the red one to the east is where we have no Bing or Mapbox at all.

**Comment by smit1678** [comment]
I've created a YAUM (yet another umap map) to organize figuring out priorities on the new release of DG imagery: http://umap.openstreetmap.fr/en/map/hot-nepal-imagery-coord_37964#9/28.0211/85.3802. Made an initial list of images in the wiki: https://github.com/hotosm/imagery-requests/wiki/Nepal-Earthquake-2015---Imagery-List. 

Next steps is to identify priority areas based on map resolution gaps.

**Comment by smit1678** [comment]
Based on @cgiovando's work [here](http://umap.openstreetmap.fr/en/map/hot-imagery-coordination_37804#9/27.9338/85.6384), I think there are two candidates for priority: 
- 347f956c8265c7e9187651b0b131c240 | 2/21/15 5:14  | WV02   | 0.070997   | 103001003E1DCD00
- bf1992be159b8501d93f71b2d7fc3506 | 2/13/13 5:20  | WV02   | 0          | 103001001FBDE200

Has anyone processed these already? 

cc @d3netxer @mikelmaron

**Comment by mikelmaron** [comment]
No prob on other uMaps ... but please update osm wiki link(s) if you get a chance. 

```
 On Monday, April 27, 2015 4:48 PM, Nate Smith <notifications@github.com> wrote:
```

 Based on @cgiovando's work here, I think there are two candidates for priority:    
- 347f956c8265c7e9187651b0b131c240 | 2/21/15 5:14 | WV02 | 0.070997 | 103001003E1DCD00
- bf1992be159b8501d93f71b2d7fc3506 | 2/13/13 5:20 | WV02 | 0 | 103001001FBDE200
  Has anyone processed these already? cc @d3netxer @mikelmaron —

**Comment by d3netxer** [comment]
We haven't processed those two (or any other ones yet)
What is 347f956c8265c7e9187651b0b131c240 | 2/21/15 5:14 | WV02 | 0.070997 | 103001003E1DCD00 supposed to cover? The thin area the @cgiovando specified as having low-res Bing coverage seems to be to the West of that strip

**Comment by d3netxer** [comment]
wow, some good WV3 shots came in today covering Kathmandu

**Comment by smit1678** [comment]
> We haven't processed those two (or any other ones yet)

If everyone agrees these are good initial priorities, we can split these out into tickets. @d3netxer - you and I can then split trying to get these downloaded. 

> What is 347f956c8265c7e9187651b0b131c240 | 2/21/15 5:14 | WV02 | 0.070997 | 103001003E1DCD00 supposed to cover? The thin area the @cgiovando specified as having low-res Bing coverage seems to be to the West of that strip

@d3netxer Yeah trying to capture this area, but only capturing part of the entire area: 

![hot imagery coordination - umap 2015-04-27 18-15-08](https://cloud.githubusercontent.com/assets/796838/7359163/64268388-ed09-11e4-9c6a-af925a946ce3.png)

Suggestions? 

> wow, some good WV3 shots came in today covering Kathmandu

Yeah, @camillacaros just updated #8, they started looking to make that available.

**Comment by d3netxer** [comment]
We could cover part of the Borang area with this:

2015-02-10 14:50:08 UTC
    103001003D381400

https://browse.digitalglobe.com/imagefinder/showBrowseMetadata?catalogId=103001003D381400

**Comment by d3netxer** [comment]
![screen shot 2015-04-27 at 11 45 42 pm](https://cloud.githubusercontent.com/assets/2665840/7362499/bfd5998e-ed37-11e4-8759-579daf226715.png)

well, I guess it covers at least part of the area you are pointing to. Do you want us to proceed with this scene?

**Comment by d3netxer** [comment]
processing on borang area is progressing at good pace, aiming to finish today.

**Comment by pjdufour** [comment]
See image coord list for info on Borang.

**Comment by smit1678** [comment]
Closing out in preference to #15
