### ISSUE TITLE
Task status

### ISSUE THREAD

**Issue by danielfdsilva** [hotosm/imagery-requests#60]
> More specific aerial surveying and imagery processing status types should be used

Currently the tasks can have one of the following statuses:
- Open
- In progress
- Completed

@smit1678 could you provide the list of statuses to use?

**Comment by smit1678** [comment]
Changing these is lower priority at the moment. @cgiovando what do you think about these that try to capture both aerial surveying and imagery processing: 

* Open
* Collection planned (In progress)
* Collection completed (In progress)
* Processing in progress
* Completed
* Canceled

**Comment by smit1678** [comment]
I'd almost recommend keeping these simple as we test this out and get feedback. But open to ideas.
