### ISSUE TITLE
Add Digital Globe Base map

### ISSUE THREAD

**Issue by danielfdsilva** [hotosm/imagery-requests#62]
We need a DG account to be able to use the maps.
@smit1678 is there an account you can share with me?

**Comment by smit1678** [comment]
@danielfdsilva Let's use this style: `mapbox://styles/digitalglobe/ciode6t5k0081aqm7k06dod4v` and this token: `pk.eyJ1IjoiZGlnaXRhbGdsb2JlIiwiYSI6ImNpdHZtM3FjbzAwNjYyem40c3FlNG11eGkifQ.dxTyi-e8nUFGtGQON78xQA`. This is a testing token for now and so we'll want to change this out once we're ready.
