### ISSUE TITLE
Add bing base map

### ISSUE THREAD

**Issue by danielfdsilva** [hotosm/imagery-requests#63]
@nbumbarger could you share your research on using bing maps with mapbox?

**Comment by smit1678** [comment]
Imagery API details should be here: https://msdn.microsoft.com/en-us/library/ff701721.aspx. You can use this token to test (under my account for now, we'll move to HOT's azure account when ready to go live): `AtkxF7FKErIxXHv8OUFVZhCT3iwdiPQIR1sY1dFD9IAJYB6fm6VehB4wQMdAOaIF `
