### ISSUE TITLE
Improve information hierarchy and clarity

### ISSUE THREAD

**Issue by danielfdsilva** [hotosm/imagery-requests#65]
Overarching issue to further discussion on improving information hierarchy and clarity.
We'll be listing smaller items to help achieve this.

**Comment by danielfdsilva** [comment]
After some discussion it was clear that the maps need to be improved. Adding interactivity and more details will help with the information clarity:

- Color code the markers according to the status
- On request pages show the different tasks on the map instead of the request bbox
- Show a tooltip when clicking a polygon with more information (basically what's on the cards)
- On task pages show the other request tasks grayed out to provide some context.

**Comment by smit1678** [comment]
Let's add: 

  - tooltip visible on load for most recently updated request on landing view
  - indicate task status within the polygon on request view

**Comment by danielfdsilva** [comment]
Most of this was implemented (https://github.com/hotosm/imagery-requests/pull/67). To be done is some final polish of the styles and status colors.

**Comment by smit1678** [comment]
👍  Closing this out in preference for individual tickets going forward.
