### ISSUE TITLE
Add request button placement

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#84]
The Add Request button feels slightly out of place by by forcing the map down once you login. @ascalamogna Can you give a quick rundown of your reasoning for this location? Would it match the Imagery Search section better by putting it in the upper right?

![](https://api.monosnap.com/rpc/file/download?id=wRVCT7iHnxt93yJPrjMj6usaQCVMNO)

**Comment by ascalamogna** [comment]
@smit1678 yeah I agree, I think we could move it to the upper right. That's a common design pattern, for example, see the edit or add new issue button placement on github.
