### ISSUE TITLE
Improve indication that you can click to change maps

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#88]
On the imagery search page, look to improve the indication that you can click to change the maps. Right now there is no mouse indication or visual indication of the map selected.

**Comment by sharkinsspatial** [comment]
Can we consider having pan and zoom operations only enabled on the main map?  In this case the we can change the cursor style for the child maps to pointer with tool tip indicating that the map is selectable.

**Comment by smit1678** [comment]
@sharkinsspatial 👍  I like that idea. What do you think of also having a visual indication that the main is "selected"?

**Comment by sharkinsspatial** [comment]
I will also include a highlighted box around the currently selected child map to help clarify that it is currently selected.
