### ISSUE TITLE
Imagery Request: Afsay (Afghanistan Avalanches, Feb 2017)

### ISSUE THREAD

**Issue by cgiovando** [hotosm/imagery-requests#90]
**Description:**
Heavy snowfall at the beginning of the month have caused several avalanches in NE Afghanistan, causing >100 casualties and destroying several villages. The full extent and impact of the disaster is still unknown, but there are reports from OCHA and other agencies from specific villages, mostly in the Nuristan province.

According to this report, 57 people died in Afsay (Barg-e-Matal District). The small village lies at the bottom of the valley near the border with Pakistan, ~240km NE of Kabul.

![afsay location](https://cloud.githubusercontent.com/assets/10201533/22911101/e11d44d4-f212-11e6-9c5a-356e2527e908.jpg)

High resolution imagery is available in Google Earth/Maps and shows the several buildings that were probably affected by the avalanches:

![afsay - google earth 2010](https://cloud.githubusercontent.com/assets/10201533/22911137/0ac8724a-f213-11e6-98e9-201cdee31c64.jpg)

**Links:**
- EU ECHO [map](http://reliefweb.int/sites/reliefweb.int/files/resources/20170206_PakistanAfghanistan_SnowAvalanches.pdf) of affected provinces (Feb 6)
- OCHA [flash report](http://reliefweb.int/sites/reliefweb.int/files/resources/OCHA%20Afghanistan%20Nuristan%20Avalanche%20Flash%20Update%208%20February%202017.pdf) (Feb 8)
- IFRC [blog post](http://www.ifrc.org/en/news-and-media/news-stories/asia-pacific/afghanistan/severe-snowstorms-bring-tragedy-in-afghanistan-and-pakistansevere-snowstorms-bring-tragedy-in-afghanistan-and-pakistan-73842/) and report (Feb 9)

**Request extent**: 
At the moment this request focuses on the area around Afsay. Below is a map with the AOI:

![aoi-out](https://cloud.githubusercontent.com/assets/10201533/22911694/e7734830-f215-11e6-8945-728917f70d4c.jpg)

Zoomed in map:

![aoi](https://cloud.githubusercontent.com/assets/10201533/22911709/f3efbb5c-f215-11e6-8e3b-52b57bd6c7c7.jpg)

Links to [live map](http://bl.ocks.org/d/598d1f9e41a7b271fc9d8f8df83448a0) and [GeoJSON.io](http://geojson.io/#id=gist:anonymous/c3be845f5e6af406f6f01abe3dd1a634&map=11/35.7916/71.3850) for download in [GeoJSON](https://gist.githubusercontent.com/anonymous/c3be845f5e6af406f6f01abe3dd1a634/raw/f327c977f557c8fc8379585daa1cec379a6cb3d0/map.geojson) and other formats.

**Issue with current imagery quality:**
Imagery in Mapbox and Bing is low resolution for the area around Afsay

**Level of urgency:**
	- [ ] Low
	- [ ] Medium
	- [x] **High**

**Pre-event imagery is needed to create the baseline map data in OpenStreetMap. Any post-event imagery (from Feb 5, 2017) will be used for damage assessment and response**

**Comment by smit1678** [comment]
@cgiovando Are there any links to who is working on the ground that we're working with? Context for who and what partners are we directly working with that will use the imagery and data?

**Comment by cgiovando** [comment]
The primary requester of baseline map data is the World Bank, in order to conduct damage assessment. I expect the same data to be used by other responding organizations though.

**Comment by cgiovando** [comment]
Focus from requesting organization shifted to another affected area, so I'm closing this thread for now.
