### ISSUE TITLE
Cannot read property 'activeTasks' on Dashboard page

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#91]
When logged in and viewing the Dashboard page, page is not fully loading and getting javascript errors in the console on Chrome. 

`Uncaught (in promise) TypeError: Cannot read property 'activeTasks' of undefined`. 

It seems that the call to `https://imagery-coordination.herokuapp.com/users/auth0%7C5845f88328be27504a2bf3a4/tasks?scope=created&includeStats=true&limit=10` is returning `Unauthorized`. 

![](https://api.monosnap.com/rpc/file/download?id=kfnRm4ISCPbZiNWSYqpWiJwCizqVE0)

**Comment by danielfdsilva** [comment]
Fixed
